// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using turno_clave_API.Infrastructure.Data;

#nullable disable

namespace turno_clave_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217184227_add_professional_table_and_relationship")]
    partial class add_professional_table_and_relationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_id");

                    b.Property<int?>("BusinessId1")
                        .HasColumnType("integer")
                        .HasColumnName("business_id1");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<int?>("ClientId1")
                        .HasColumnType("integer")
                        .HasColumnName("client_id1");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_time");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<int?>("ServiceId1")
                        .HasColumnType("integer")
                        .HasColumnName("service_id1");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_appointments");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("i_x_appointments_business_id");

                    b.HasIndex("BusinessId1")
                        .HasDatabaseName("i_x_appointments_business_id1");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("i_x_appointments_client_id");

                    b.HasIndex("ClientId1")
                        .HasDatabaseName("i_x_appointments_client_id1");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("i_x_appointments_service_id");

                    b.HasIndex("ServiceId1")
                        .HasDatabaseName("i_x_appointments_service_id1");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_id");

                    b.Property<int?>("BusinessId1")
                        .HasColumnType("integer")
                        .HasColumnName("business_id1");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("p_k_availabilities");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("i_x_availabilities_business_id");

                    b.HasIndex("BusinessId1")
                        .HasDatabaseName("i_x_availabilities_business_id1");

                    b.ToTable("availabilities");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.AvailabilityException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_id");

                    b.Property<int?>("BusinessId1")
                        .HasColumnType("integer")
                        .HasColumnName("business_id1");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_time");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_availability_exceptions");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("i_x_availability_exceptions_business_id");

                    b.HasIndex("BusinessId1")
                        .HasDatabaseName("i_x_availability_exceptions_business_id1");

                    b.ToTable("availability_exceptions");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_businesses");

                    b.ToTable("businesses");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_id");

                    b.Property<int?>("BusinessId1")
                        .HasColumnType("integer")
                        .HasColumnName("business_id1");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_clients");

                    b.HasIndex("BusinessId1")
                        .HasDatabaseName("i_x_clients_business_id1");

                    b.HasIndex("BusinessId", "Email")
                        .HasDatabaseName("i_x_clients_business_id_email");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Professional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_professional");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("i_x_professional_business_id");

                    b.ToTable("professional");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_id");

                    b.Property<int?>("BusinessId1")
                        .HasColumnType("integer")
                        .HasColumnName("business_id1");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_services");

                    b.HasIndex("BusinessId1")
                        .HasDatabaseName("i_x_services_business_id1");

                    b.HasIndex("BusinessId", "Name")
                        .HasDatabaseName("i_x_services_business_id_name");

                    b.ToTable("services");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("i_x_users_business_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_appointments__businesses_business_id");

                    b.HasOne("turno_clave_API.Domain.Entities.Business", null)
                        .WithMany("Appointments")
                        .HasForeignKey("BusinessId1")
                        .HasConstraintName("f_k_appointments__businesses_business_id1");

                    b.HasOne("turno_clave_API.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_appointments__clients_client_id");

                    b.HasOne("turno_clave_API.Domain.Entities.Client", null)
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId1")
                        .HasConstraintName("f_k_appointments__clients_client_id1");

                    b.HasOne("turno_clave_API.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_appointments__services_service_id");

                    b.HasOne("turno_clave_API.Domain.Entities.Service", null)
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId1")
                        .HasConstraintName("f_k_appointments__services_service_id1");

                    b.Navigation("Business");

                    b.Navigation("Client");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Availability", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_availabilities__businesses_business_id");

                    b.HasOne("turno_clave_API.Domain.Entities.Business", null)
                        .WithMany("Availabilities")
                        .HasForeignKey("BusinessId1")
                        .HasConstraintName("f_k_availabilities__businesses_business_id1");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.AvailabilityException", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_availability_exceptions__businesses_business_id");

                    b.HasOne("turno_clave_API.Domain.Entities.Business", null)
                        .WithMany("AvailabilityExceptions")
                        .HasForeignKey("BusinessId1")
                        .HasConstraintName("f_k_availability_exceptions__businesses_business_id1");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Client", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_clients_businesses_business_id");

                    b.HasOne("turno_clave_API.Domain.Entities.Business", null)
                        .WithMany("Clients")
                        .HasForeignKey("BusinessId1")
                        .HasConstraintName("f_k_clients_businesses_business_id1");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Professional", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Business", "Business")
                        .WithMany("Professionals")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_professional_businesses_business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Service", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_services_businesses_business_id");

                    b.HasOne("turno_clave_API.Domain.Entities.Business", null)
                        .WithMany("Services")
                        .HasForeignKey("BusinessId1")
                        .HasConstraintName("f_k_services_businesses_business_id1");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.User", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Business", null)
                        .WithMany("Users")
                        .HasForeignKey("BusinessId")
                        .HasConstraintName("f_k_users_businesses_business_id");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Business", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");

                    b.Navigation("AvailabilityExceptions");

                    b.Navigation("Clients");

                    b.Navigation("Professionals");

                    b.Navigation("Services");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Client", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Service", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
