// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using turno_clave_API.Infrastructure.Data;

#nullable disable

namespace turno_clave_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515230049_add_is_public_link_enabled_to_business")]
    partial class add_is_public_link_enabled_to_business
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_time");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("integer")
                        .HasColumnName("professional_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_appointments");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("i_x_appointments_business_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("i_x_appointments_client_id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_appointments_external_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("i_x_appointments_service_id");

                    b.HasIndex("ProfessionalId", "StartDateTime")
                        .HasDatabaseName("i_x_appointments_professional_id_start_date_time");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.AvailabilityException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeOnly?>("EndDateTime")
                        .IsRequired()
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_date_time");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<int?>("ProfessionalId")
                        .HasColumnType("integer")
                        .HasColumnName("professional_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<TimeOnly?>("StartDateTime")
                        .IsRequired()
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_date_time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_availability_exceptions");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("i_x_availability_exceptions_business_id");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("i_x_availability_exceptions_professional_id");

                    b.ToTable("availability_exceptions");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublicLinkEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public_link_enabled");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string[]>("PaymentMethods")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("payment_methods")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_businesses");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("i_x_businesses_slug");

                    b.ToTable("businesses");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.BusinessAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_business_availabilities");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("i_x_business_availabilities_business_id");

                    b.ToTable("business_availabilities", (string)null);
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_clients");

                    b.HasIndex("BusinessId", "Email")
                        .HasDatabaseName("i_x_clients_business_id_email");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Professional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_id");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_professionals");

                    b.HasIndex("BusinessId", "Name")
                        .HasDatabaseName("i_x_professionals_business_id_name");

                    b.ToTable("professionals");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.ProfessionalAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("integer")
                        .HasColumnName("professional_id");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("p_k_professional_availabilities");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("i_x_professional_availabilities_professional_id");

                    b.ToTable("professional_availabilities");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.ProfessionalService", b =>
                {
                    b.Property<int>("ProfessionalId")
                        .HasColumnType("integer")
                        .HasColumnName("professional_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.HasKey("ProfessionalId", "ServiceId")
                        .HasName("p_k_professional_service");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("i_x_professional_service_service_id");

                    b.ToTable("professional_service");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_external_id");

                    b.HasKey("Id")
                        .HasName("p_k_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("i_x_refresh_tokens_token");

                    b.HasIndex("UserExternalId")
                        .HasDatabaseName("i_x_refresh_tokens_user_external_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_services");

                    b.HasIndex("BusinessId", "Name")
                        .HasDatabaseName("i_x_services_business_id_name");

                    b.ToTable("services");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ActiveBusinessExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_business_external_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.UserBusiness", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("UserId", "BusinessId")
                        .HasName("p_k_user_businesses");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("i_x_user_businesses_business_id");

                    b.ToTable("user_businesses");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Business", "Business")
                        .WithMany("Appointments")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_appointments__businesses_business_id");

                    b.HasOne("turno_clave_API.Domain.Entities.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_appointments__clients_client_id");

                    b.HasOne("turno_clave_API.Domain.Entities.Professional", "Professional")
                        .WithMany("Appointments")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_appointments__professionals_professional_id");

                    b.HasOne("turno_clave_API.Domain.Entities.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_appointments__services_service_id");

                    b.Navigation("Business");

                    b.Navigation("Client");

                    b.Navigation("Professional");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.AvailabilityException", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Business", "Business")
                        .WithMany("AvailabilityExceptions")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_availability_exceptions__businesses_business_id");

                    b.HasOne("turno_clave_API.Domain.Entities.Professional", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .HasConstraintName("f_k_availability_exceptions__professionals_professional_id");

                    b.Navigation("Business");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.BusinessAvailability", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Business", "Business")
                        .WithMany("BusinessAvailabilities")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_business_availabilities_businesses_business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Client", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Business", "Business")
                        .WithMany("Clients")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_clients_businesses_business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Professional", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Business", "Business")
                        .WithMany("Professionals")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_professionals_businesses_business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.ProfessionalAvailability", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Professional", "Professional")
                        .WithMany("Availabilities")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_professional_availabilities_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.ProfessionalService", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Professional", "Professional")
                        .WithMany("ProfessionalServices")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_professional_service_professionals_professional_id");

                    b.HasOne("turno_clave_API.Domain.Entities.Service", "Service")
                        .WithMany("ProfessionalServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_professional_service__services_service_id");

                    b.Navigation("Professional");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Service", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Business", "Business")
                        .WithMany("Services")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_services_businesses_business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.UserBusiness", b =>
                {
                    b.HasOne("turno_clave_API.Domain.Entities.Business", "Business")
                        .WithMany("UserBusinesses")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_businesses_businesses_business_id");

                    b.HasOne("turno_clave_API.Domain.Entities.User", "User")
                        .WithMany("UserBusinesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_businesses_users_user_id");

                    b.Navigation("Business");

                    b.Navigation("User");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Business", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AvailabilityExceptions");

                    b.Navigation("BusinessAvailabilities");

                    b.Navigation("Clients");

                    b.Navigation("Professionals");

                    b.Navigation("Services");

                    b.Navigation("UserBusinesses");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Client", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Professional", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");

                    b.Navigation("ProfessionalServices");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.Service", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ProfessionalServices");
                });

            modelBuilder.Entity("turno_clave_API.Domain.Entities.User", b =>
                {
                    b.Navigation("UserBusinesses");
                });
#pragma warning restore 612, 618
        }
    }
}
